### ISSUE TITLE
online demo please :)?

### ISSUE THREAD

**Issue by winkler1** [chenzihui/react-splicer#1]
Hi-
 Sounds interesting, but could you put up a demo? I ran the example, but it was not really clear what's going on.... a demo populated with realistic test data would get the use case across better.
Thanks

**Comment by chenzihui** [comment]
Sure, I'll work on an online demo

**Comment by chenzihui** [comment]
Have put up an online demo - http://chenzihui.github.io/react-splicer/ :smile:
